sudo: required
services:
  - docker
before_install:
  - docker build -t leonmuzire/docker-react -f Dockerfile .
script:
  - docker run -e CI=true leonmuzire/docker-react npm test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-eu-north-1-289345405072"
  bucket_path: "frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY