sudo: required
services:
  - docker

before_install:
  # Build only the tester stage
  - docker build --target tester -t leonmuzire/docker-react-test -f Dockerfile .

script:
  # Run tests using the tester stage
  - docker run -e CI=true leonmuzire/docker-react-test npm test -- --coverage

  # Build the full production image
  - docker build -t leonmuzire/docker-react-prod -f Dockerfile .

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-eu-north-1-289345405072"
  bucket_path: "frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY